server:
  port: 18182

project:
  version: @project.version@

spring:
  data:
    redis:
      # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
      #    host: 192.168.1.241
      host: 192.168.1.241
      # [必须修改] 端口号
      port: 6379
      # [可选] 数据库 DB
      database: 15
      # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
      password:
      # [可选] 超时时间
      timeout: 10000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456a
    url: jdbc:mysql://192.168.1.241:3306/gb28181_docking_platform?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#  profiles:
#    active: local

gb28181:
  # 作为28181服务器的配置
  sip:
    # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
    # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
    # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
    ip:
#      - 10.27.0.1
      - 192.168.0.195
      #- 172.16.1.90
#      - 192.168.10.195
#      - 10.10.10.20
#      - 10.27.0.6
    # [可选] 28181服务监听的端口
    port: 15060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4405010000
    # [可选]
    id: 44050100002000000002
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: 123456
    expire: 3600
    transport: "UDP"
  server:
#    ip: 192.168.10.32
    ip: 192.168.3.12
    port: 5060
    password: 123456
    domain: 4405010000
    id: 44050100002000000001

media:
  local:
    hook: http://192.168.0.195:18182/zlm/hook
  ip: 192.168.3.12
  url: 'http://192.168.3.12:5082'
  #  url: 'http://10.10.10.200:12580/anything/'
  id: amrWMKmbKqoBjRQ9
#  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  secret: 4155cca6-2f9f-11ee-85e6-8de4ce2e7333
  rtmp:
    port: 1937
proxy:
  device:
    # 代理的视频接口地址, 用于获取历史视频
    # 参数 device_id, begin_time, end_time
    #url: http://192.168.2.3:18183
    url: http://10.10.10.20:18183
    #url: http://192.168.1.241:28181
ffmpeg-support:
  task:
    # 最大同时推流任务数, <= 0 时不做限制
    max: 4
#  ffmpeg: /usr/bin/ffmpeg/ffmpeg
#  ffprobe: /usr/bin/ffmpeg/ffprobe
  ffmpeg: C:\ffmpeg\bin\ffmpeg.exe
  ffprobe: D:\Soft\Captura\ffmpeg\ffprobe.exe
#  rtp:
#    download: -i
#    input: -re -i
#    output: -vcodec h264 -acodec aac -preset ultrafast -vf scale=640:-1 -f flv
#  debug:
#    download: false
#    input: false
#    output: false
  rtp:
    #input: -thread_queue_size 128 -re -i http://192.168.3.12:5081/live/test.live.flv
    #input: -re -i
    input:  -rw_timeout 60000000 -re -i
    #output: -tune zerolatency -vcodec libx264 -acodec aac -preset ultrafast -vf scale=640:-1 -f flv #rtp_mpegts
    #output: -vcodec libx264 -acodec aac -vf scale=640:-1 -f rtp_mpegts # -rtsp_transport tcp
    # 拉取4倍速流文件 还原速率
    #output: -filter:v "setpts=4.0*PTS" -tune zerolatency -vcodec libx264 -acodec aac -preset ultrafast -vf scale=640:-1 -f flv
    # 下载 正常速率
    #output: -r 30 -tune zerolatency -vcodec libx264 -acodec aac -preset ultrafast -vf scale=640:-1 -f flv
    output: -r 30 -vcodec libx264 -acodec aac -filter:v "setpts=1*PTS" -preset ultrafast -flvflags no_duration_filesize -bf 0 -max_interleave_delta 0 -f flv
    #download: -i E:\Repository\other\happytime-gb28181-device-x64\666.mp4 -filter:v "setpts=4.0*PTS"
    download: -i
    download-speed: 4.0
  debug:
    download: false
    input: false
    output: false
  # 是否通过 zlm 调用 ffmpeg
  use-zlm-ffmpeg: false

# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback.xml
